# Site settings
title: "wanho1108.log"
email: "wanho1108@gmail.com"
description: ""
baseurl: ""
url: "http://wanho1108.github.io"
google_analytics: "UA-138408391-1"
permalink: none

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/page:num/"
# pagination:
#   enabled: true
#   per_page: 5
#   sort_reverse: true
#   title: ':title'
#   trail: 
#     before: 2
#     after: 2 

# Style
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
